name: Eslint

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**.ts"

jobs:
  lint:
    name: "Eslint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: pnpm install

      - name: Run Eslint
        run: node ./linter.js eslint
