name: Type Check

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**.ts"

jobs:
  type-check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Eslint
        run: node ./linter.js typecheck
